[2023-01-04T19:38:22.660+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T19:38:20.609062+00:00 [queued]>
[2023-01-04T19:38:22.671+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T19:38:20.609062+00:00 [queued]>
[2023-01-04T19:38:22.672+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:38:22.672+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T19:38:22.672+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:38:22.689+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_clean_transform_dataset_task> on 2023-01-04 19:38:20.609062+00:00
[2023-01-04T19:38:22.693+0000] {standard_task_runner.py:55} INFO - Started process 273 to run task
[2023-01-04T19:38:22.697+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'extract_clean_transform_dataset_task', 'manual__2023-01-04T19:38:20.609062+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpiyjoi6x8']
[2023-01-04T19:38:22.700+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask extract_clean_transform_dataset_task
[2023-01-04T19:38:22.767+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T19:38:20.609062+00:00 [running]> on host 4de77850e514
[2023-01-04T19:38:22.856+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_clean_transform_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T19:38:20.609062+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T19:38:20.609062+00:00
[2023-01-04T19:38:24.402+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:295 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T19:38:39.178+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:117 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T19:38:39.211+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:126 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T19:38:39.633+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/utils/validation.py:993 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2023-01-04T19:39:39.133+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T19:39:39.152+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=extract_clean_transform_dataset_task, execution_date=20230104T193820, start_date=20230104T193822, end_date=20230104T193939
[2023-01-04T19:39:39.206+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T19:39:39.234+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
