[2023-01-04T19:58:12.739+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T19:56:29.653292+00:00 [queued]>
[2023-01-04T19:58:12.749+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T19:56:29.653292+00:00 [queued]>
[2023-01-04T19:58:12.749+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:58:12.750+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-01-04T19:58:12.750+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T19:58:12.764+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 19:56:29.653292+00:00
[2023-01-04T19:58:12.768+0000] {standard_task_runner.py:55} INFO - Started process 507 to run task
[2023-01-04T19:58:12.771+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T19:56:29.653292+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmp7u2to5r6']
[2023-01-04T19:58:12.773+0000] {standard_task_runner.py:83} INFO - Job 87: Subtask create_dashboard_task
[2023-01-04T19:58:12.833+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T19:56:29.653292+00:00 [running]> on host 4de77850e514
[2023-01-04T19:58:12.906+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T19:56:29.653292+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T19:56:29.653292+00:00
[2023-01-04T19:58:13.771+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:4913 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T19:58:13.885+0000] {logging_mixin.py:137} INFO - 0         Kensington and Chelsea
1         Kensington and Chelsea
2         Kensington and Chelsea
3         Kensington and Chelsea
4         Kensington and Chelsea
                   ...          
148932                     Powys
148933                     Powys
148934                     Powys
148935                     Powys
148936                     Powys
Name: local_authority_ons_district, Length: 148937, dtype: object
[2023-01-04T19:58:14.009+0000] {logging_mixin.py:137} INFO - 0          Slight
1         Serious
2          Slight
3          Slight
4          Slight
           ...   
148932     Slight
148933     Slight
148934     Slight
148935     Slight
148936     Slight
Name: accident_severity, Length: 148937, dtype: object
[2023-01-04T19:58:14.044+0000] {logging_mixin.py:137} INFO - 0         30.0
1         30.0
2         30.0
3         30.0
4         30.0
          ... 
148932    60.0
148933    60.0
148934    30.0
148935    60.0
148936    60.0
Name: speed_limit, Length: 148937, dtype: object
[2023-01-04T19:58:15.530+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T19:58:15.530+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T19:58:15.536+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T19:58:15.536+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T19:58:15.537+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T19:58:15.537+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T19:58:15.555+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T19:58:15.576+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
