[2023-01-04T16:31:12.524+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:16:41.990135+00:00 [queued]>
[2023-01-04T16:31:12.533+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:16:41.990135+00:00 [queued]>
[2023-01-04T16:31:12.533+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:31:12.534+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-04T16:31:12.534+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:31:12.548+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 16:16:41.990135+00:00
[2023-01-04T16:31:12.553+0000] {standard_task_runner.py:55} INFO - Started process 938 to run task
[2023-01-04T16:31:12.556+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T16:16:41.990135+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmprtidco8e']
[2023-01-04T16:31:12.559+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask create_dashboard_task
[2023-01-04T16:31:12.622+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:16:41.990135+00:00 [running]> on host 4de77850e514
[2023-01-04T16:31:12.700+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T16:16:41.990135+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T16:16:41.990135+00:00
[2023-01-04T16:31:13.861+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T16:32:32.038+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-04T16:32:32.042+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 938. PIDs of all processes in the group: [938]
[2023-01-04T16:32:32.045+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 938
[2023-01-04T16:32:32.079+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=938, status='terminated', exitcode=0, started='16:31:11') (938) terminated with exit code 0
[2023-01-04T16:32:32.080+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-04T16:32:32.095+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
