[2023-01-04T16:34:27.593+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:32:30.140376+00:00 [queued]>
[2023-01-04T16:34:27.604+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:32:30.140376+00:00 [queued]>
[2023-01-04T16:34:27.604+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:34:27.604+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T16:34:27.605+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:34:27.623+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 16:32:30.140376+00:00
[2023-01-04T16:34:27.630+0000] {standard_task_runner.py:55} INFO - Started process 1388 to run task
[2023-01-04T16:34:27.633+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T16:32:30.140376+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpvv5v9qac']
[2023-01-04T16:34:27.635+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask create_dashboard_task
[2023-01-04T16:34:27.704+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T16:32:30.140376+00:00 [running]> on host 4de77850e514
[2023-01-04T16:34:27.787+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T16:32:30.140376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T16:32:30.140376+00:00
[2023-01-04T16:34:29.059+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T16:34:30.260+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T16:34:30.259+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T16:34:30.269+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T16:34:30.275+0000] {logging_mixin.py:137} INFO -  * Debug mode: on
[2023-01-04T16:34:30.286+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T16:34:30.287+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T16:34:30.336+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T16:34:30.355+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
