[2023-01-04T16:07:46.314+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [queued]>
[2023-01-04T16:07:46.325+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [queued]>
[2023-01-04T16:07:46.326+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:07:46.327+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-04T16:07:46.327+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:07:46.340+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 15:59:24.331300+00:00
[2023-01-04T16:07:46.346+0000] {standard_task_runner.py:55} INFO - Started process 1350 to run task
[2023-01-04T16:07:46.349+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T15:59:24.331300+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpbgwtwjen']
[2023-01-04T16:07:46.352+0000] {standard_task_runner.py:83} INFO - Job 47: Subtask create_dashboard_task
[2023-01-04T16:07:46.421+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [running]> on host 4de77850e514
[2023-01-04T16:07:46.504+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T15:59:24.331300+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T15:59:24.331300+00:00
[2023-01-04T16:07:47.816+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T16:07:49.047+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T16:07:49.047+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T16:07:49.053+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T16:07:49.054+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T16:07:49.055+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T16:07:49.055+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T16:07:49.089+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T16:07:49.108+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
