[2023-01-04T16:30:17.158+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:28:23.019739+00:00 [queued]>
[2023-01-04T16:30:17.168+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:28:23.019739+00:00 [queued]>
[2023-01-04T16:30:17.169+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:30:17.169+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T16:30:17.170+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:30:17.184+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-04 16:28:23.019739+00:00
[2023-01-04T16:30:17.191+0000] {standard_task_runner.py:55} INFO - Started process 627 to run task
[2023-01-04T16:30:17.194+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-04T16:28:23.019739+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmppw_ljekr']
[2023-01-04T16:30:17.196+0000] {standard_task_runner.py:83} INFO - Job 57: Subtask load_to_postgres
[2023-01-04T16:30:17.262+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T16:28:23.019739+00:00 [running]> on host 4de77850e514
[2023-01-04T16:30:17.346+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T16:28:23.019739+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T16:28:23.019739+00:00
[2023-01-04T16:30:18.353+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-04T16:30:18.378+0000] {logging_mixin.py:137} INFO - Accidents table already exists.
[2023-01-04T16:30:18.386+0000] {logging_mixin.py:137} INFO -  Look up table already exists.
[2023-01-04T16:30:18.388+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T16:30:18.397+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=load_to_postgres, execution_date=20230104T162823, start_date=20230104T163017, end_date=20230104T163018
[2023-01-04T16:30:18.450+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T16:30:18.476+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
